---
abstract: "allow \"before qr{...} => sub {...};\" in roles"
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::RoleQR
name: MooseX-RoleQR
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moose: 2.00
  Scalar::Does: 0.002
  namespace::sweep: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-RoleQR
  homepage: https://metacpan.org/release/MooseX-RoleQR
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-moosex-roleqr
version: 0.001
